// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// import Navbar from "./components/Navbar";
// import { CartProvider } from "./context/CartContext";

// import 'bootstrap/dist/css/bootstrap.min.css';


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       > 
//       <CartProvider>
//       <Navbar/>
//         {children}
     
//        </CartProvider>
//       </body>
//     </html>
//   );
// }



// import Navbar from "./components/Navbar";

// import 'bootstrap/dist/css/bootstrap.min.css';
// import { CartProvider } from "./context/CartContext";
// import { AuthProvider } from "./context/AuthContext";
// import Footer from "./components/Footer";

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//        <body>
//         <div className="d-flex flex-column min-vh-100">
         
//          <AuthProvider>   
//          <CartProvider>
//          <Navbar />
        
//          <main className="flex-fill">

//           {children}
          
//           </main>
       
//        </CartProvider>
//        </AuthProvider>  
//       <Footer/>
//       </div>
//       </body>
//     </html>
//   );
// }


import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="d-flex flex-column min-vh-100">
        <AuthProvider>
          <CartProvider>
            
            <Navbar />

            {/* <main className="flex-fill"> */}
              {children}
            {/* </main> */}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}