// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// import Navbar from "./components/Navbar";
// import { CartProvider } from "./context/CartContext";

// import 'bootstrap/dist/css/bootstrap.min.css';


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       > 
//       <CartProvider>
//       <Navbar/>
//         {children}
     
//        </CartProvider>
//       </body>
//     </html>
//   );
// }



// import Navbar from "./components/Navbar";

// import 'bootstrap/dist/css/bootstrap.min.css';
// import { CartProvider } from "./context/CartContext";
// import { AuthProvider } from "./context/AuthContext";
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//          <AuthProvider>
          
//       <CartProvider>
//           <Navbar />
//           {children}
//        </CartProvider>
//        </AuthProvider>
//       </body>
//     </html>
//   );
// }

// export default function Home() {
//   return (
//     <div className="container mt-5 text-center">
//       <h1>Welcome to FakeStore</h1>
//       <p className="lead">
//         This is a Next.js 13 App Router e-commerce application.
//       </p>

//       <div className="mt-4">
//         <a href="/Product" className="btn btn-primary me-3">
//           View Products
//         </a>

//         <a href="/cart" className="btn btn-success">
//           Go to Cart
//         </a>
//       </div>
//     </div>
//   );
// }

export default function Home() {
  return (
    <div className="container-fluid d-flex vh-100 align-items-center justify-content-center" style={{backgroundColor:"#f0c9e0"}}>
      <div className="text-center p-3  rounded shadow-sm "   style={{ backgroundColor: "#3c0023" }}>
        <h2 className="text-white mb-3">Welcome to SmartCart</h2>
         <p style={{color:"blue"}}>Shop your favorite products easily!</p>    
        </div>
      </div>  
  );
}




